### PR TITLE
#11 - puzzle format

### PR DESCRIPTION
**Pull request by maurezen**
Additional space.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by dmarkov** [comment]
@carlosmiranda please review this one

**Comment by carlosmiranda** [comment]
@maurezen Thanks for the pull request, I don't have any comments.

**Comment by carlosmiranda** [comment]
@rultor Let's merge please

**Comment by maurezen** [comment]
@carlosmiranda fails to merge automatically.

**Comment by carlosmiranda** [comment]
@maurezen I'm aware of the matter. Raised it in #13.

**Comment by maurezen** [comment]
@carlosmiranda right, thanks.

**Comment by yegor256** [comment]
@rultor try to merge it

**Comment by dmarkov** [comment]
@carlosmiranda Many thanks! **16 mins** were added to your account in Transaction ID `50570184`; +16 added to your rating, current score is: [+1683](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
