### PR TITLE
#8 - fixed copyrights section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this pull request.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@krzyk could you please review this PR

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk thanks, paid, **20 mins** to your account, payment ID is `50573276`... added +20 to your rating, now it is equal to [+2255](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
