### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by valery1707** [comment]
I fix build.

**Comment by valery1707** [comment]
@yegor256 I fix build

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-maven-skin#26` is not assigned, can't get performer

**Pull request closed without merging**
